### ISSUE TITLE
Обновить таблицу нод

### ISSUE THREAD

**Issue by PerchunPak** [superhub-host/wiki#17]
@katsil @RuscalWorld Напишите еще пожалуйста ниже какие новые ноды и какие убрать? Например про blue не помню, она работает еще или уже нет?

[(Таблица нод сейчас)](https://github.com/superhub-host/wiki/blob/61a7a713dde77653b0a182fcb85e9a183168e19b/pages/docs/ip.md)

**Comment by katsil** [comment]
einstein.host.mineserver.xyz
rutherford.host
newton
cult
fourier
тестовый: wind

**Comment by katsil** [comment]
все текущие ноды
